'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/Nav";
import { usePathname } from "next/navigation";
import { useEffect } from "react";
import { CheckedItemsContext } from "@/CheckedItemsContext";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const [checkedItems, setCheckedItems] = useState<Record<string, boolean>>({});

  return (
    <CheckedItemsContext.Provider value={{ checkedItems, setCheckedItems }}>
    <html lang="en">
      {!pathname.includes("/register") && <NavBar />}
      <body className={`${inter.className} ${pathname.includes("/register") ? '' : 'pt-[56px]'} bg-warm-yellow`}>{children}</body>
    </html>
    </CheckedItemsContext.Provider>
  );
}