import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import NavBar from "../../components/Nav";
import { usePathname } from "next/navigation";
// import { useEffect } from "react";
import NavbarContextProvider from "@/contexts/NavbarContext";
import CheckedItemsContextProvider from "@/contexts/CheckedItemsContext";
// import { useState } from "react";
import { NextIntlClientProvider, useMessages } from "next-intl";
import ClientNavBar from "./ClientNavbar";
import SelectedJobProvider from "@/contexts/SelectedJobContext";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.className} pt-[56px] bg-warm-yellow`}>
        <NextIntlClientProvider locale={locale} messages={useMessages()}>
          <NavbarContextProvider>
            <CheckedItemsContextProvider>
              <SelectedJobProvider>
                <NavBar />
                {children}
              </SelectedJobProvider>
            </CheckedItemsContextProvider>
          </NavbarContextProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}